//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Water_Environment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donate
    {
        public int DonateId { get; set; }
        public string DonateCode { get; set; }
        public string Content { get; set; }
        public int UserId { get; set; }
        public Nullable<int> MoneyDonate { get; set; }
        public System.DateTime CreateOn { get; set; }
        public bool IsDonateSuccess { get; set; }
    
        public virtual User User { get; set; }
    }
}
